@echo off
echo Iniciando entorno de desarrollo negociApp...
if not exist .venv (
    echo Creando entorno virtual...
    python -m venv .venv
)
call .venv\Scripts\activate
echo Instalando dependencias (si faltan)...
pip install -r requirements.txt
echo Ejecutando Servidor...
uvicorn app.main:app --reload
pause
