"""fix: append expiration date in products

Revision ID: 0480628b8930
Revises: b1f063fa4a67
Create Date: 2026-02-12 08:29:20.988258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0480628b8930'
down_revision: Union[str, None] = 'b1f063fa4a67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('expiration_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'expiration_date')
    # ### end Alembic commands ###
