"""extend_notes_purchase_order

Revision ID: 1e6948e2e20a
Revises: 167ef54e6fc6
Create Date: 2026-03-09 08:29:12.544265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e6948e2e20a'
down_revision: Union[str, None] = '167ef54e6fc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('purchase_orders', 'notes',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=600),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('purchase_orders', 'notes',
               existing_type=sa.String(length=600),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    # ### end Alembic commands ###
