"""update model of tenant and developed new models

Revision ID: 3f5dfb7f16e9
Revises: 0480628b8930
Create Date: 2026-02-20 21:22:49.482473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f5dfb7f16e9'
down_revision: Union[str, None] = '0480628b8930'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('grace_period_used', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'grace_period_used')
    # ### end Alembic commands ###
