"""add_product_type_alert_fields_and_notification_types

Revision ID: 6b2f0122295c
Revises: 8170ed9d4e97
Create Date: 2026-05-11 13:41:54.270145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '6b2f0122295c'
down_revision: Union[str, None] = '8170ed9d4e97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('min_stock_alert', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('enable_alert', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_alerts_product_id'), 'stock_alerts', ['product_id'], unique=False)
    op.create_index(op.f('ix_stock_alerts_tenant_id'), 'stock_alerts', ['tenant_id'], unique=False)
    op.add_column('notifications', sa.Column('notes', sa.Text(), nullable=True))
    op.alter_column('notifications', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    
    # Crear el tipo enum si no existe
    op.execute("""
        DO $$ BEGIN 
            CREATE TYPE producttype AS ENUM ('RAW_MATERIAL', 'PRODUCT_ELABORATED', 'PRODUCT_PURCHASED'); 
        EXCEPTION WHEN duplicate_object THEN null; 
        END $$;
    """)
    
    # Agregar columnas con el tipo enum existente
    op.add_column('products', sa.Column('product_type', postgresql.ENUM('RAW_MATERIAL', 'PRODUCT_ELABORATED', 'PRODUCT_PURCHASED', name='producttype', create_type=False), nullable=False, server_default='RAW_MATERIAL'))
    op.add_column('products', sa.Column('min_stock_alert', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('products', sa.Column('enable_alert', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'enable_alert')
    op.drop_column('products', 'min_stock_alert')
    op.drop_column('products', 'product_type')
    op.alter_column('notifications', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('notifications', 'notes')
    op.drop_index(op.f('ix_stock_alerts_tenant_id'), table_name='stock_alerts')
    op.drop_index(op.f('ix_stock_alerts_product_id'), table_name='stock_alerts')
    op.drop_table('stock_alerts')
    op.execute('DROP TYPE IF EXISTS producttype')
    # ### end Alembic commands ###
