"""transform_module

Revision ID: 7bf549de4a28
Revises: 1e6948e2e20a
Create Date: 2026-03-11 00:58:19.622494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bf549de4a28'
down_revision: Union[str, None] = '1e6948e2e20a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transforms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transforms_tenant_id'), 'transforms', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_transforms_user_id'), 'transforms', ['user_id'], unique=False)
    op.create_table('transforms_input',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transform_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['transform_id'], ['transforms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transforms_input_product_id'), 'transforms_input', ['product_id'], unique=False)
    op.create_index(op.f('ix_transforms_input_transform_id'), 'transforms_input', ['transform_id'], unique=False)
    op.create_table('transforms_output',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transform_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['transform_id'], ['transforms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transforms_output_product_id'), 'transforms_output', ['product_id'], unique=False)
    op.create_index(op.f('ix_transforms_output_transform_id'), 'transforms_output', ['transform_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transforms_output_transform_id'), table_name='transforms_output')
    op.drop_index(op.f('ix_transforms_output_product_id'), table_name='transforms_output')
    op.drop_table('transforms_output')
    op.drop_index(op.f('ix_transforms_input_transform_id'), table_name='transforms_input')
    op.drop_index(op.f('ix_transforms_input_product_id'), table_name='transforms_input')
    op.drop_table('transforms_input')
    op.drop_index(op.f('ix_transforms_user_id'), table_name='transforms')
    op.drop_index(op.f('ix_transforms_tenant_id'), table_name='transforms')
    op.drop_table('transforms')
    # ### end Alembic commands ###
