"""add_payment_method_column

Revision ID: 8170ed9d4e97
Revises: add_orderstatus_values
Create Date: 2026-05-11 09:34:44.971767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8170ed9d4e97'
down_revision: Union[str, None] = 'add_orderstatus_values'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('keep_alive_log')
    # Crear el tipo enum primero si no existe
    op.execute("DO $$ BEGIN CREATE TYPE paymentmethod AS ENUM ('EFECTIVO', 'MERCADOPAGO', 'APP_COMIDA', 'TRANSFERENCIA', 'OTRO'); EXCEPTION WHEN duplicate_object THEN null; END $$;")
    # Agregar la columna usando el tipo enum existente
    op.add_column('client_orders', sa.Column('payment_method', postgresql.ENUM('EFECTIVO', 'MERCADOPAGO', 'APP_COMIDA', 'TRANSFERENCIA', 'OTRO', name='paymentmethod', create_type=False), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_orders', 'payment_method')
    op.execute('DROP TYPE IF EXISTS paymentmethod')
    op.create_table('keep_alive_log',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('user_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='keep_alive_log_pkey')
    )
    # ### end Alembic commands ###
