import enum

class PlanType(str, enum.Enum):
    FREE_FOREVER = "FREE_FOREVER"
    FREE_TRIAL_1_MONTH = "FREE_TRIAL_1_MONTH"
    PAID_MONTHLY = "PAID_MONTHLY"
    PAID_YEARLY = "PAID_YEARLY"

class PaymentStatus(str, enum.Enum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    CANCELED = "CANCELED"

class PaymentType(str, enum.Enum):
    PAGO_MENSUAL = "PAGO_MENSUAL"
    PAGO_ANUAL = "PAGO_ANUAL"
    

class Roles(str, enum.Enum):
    ADMIN = "ADMIN"
    COMPANY = "COMPANY"
    EMPLOYEE = "EMPLOYEE"

class NotificationStatus(str, enum.Enum):
    PENDING = "PENDING"
    RESOLVED = "RESOLVED"
    IGNORED = "IGNORED"

class NotificationType(str, enum.Enum):
    RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST"
    STOCK_LOW_ALERT = "STOCK_LOW_ALERT"
    PRODUCTION_REQUEST = "PRODUCTION_REQUEST"
    PRODUCTION_COMPLETED = "PRODUCTION_COMPLETED"
    PRODUCTION_CANCELLED = "PRODUCTION_CANCELLED"
    SALE_CANCELLED = "SALE_CANCELLED"
    SALE_REJECTED = "SALE_REJECTED"
    ORDER_DELIVERY_TODAY = "ORDER_DELIVERY_TODAY"

class WasteReason(str, enum.Enum):
    ROTTEN = "ROTTEN"
    BROKEN = "BROKEN"
    EXPIRED = "EXPIRED"
    OTHER = "OTHER"
    
class PurchaseRequestStatus(str, enum.Enum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    CANCELED = "CANCELED"

class TransactionType(str, enum.Enum):
    IN = "IN"
    OUT = "OUT"
    ADJUSTMENT = "ADJUSTMENT"

class PurchaseOrderStatus(str, enum.Enum):
    DRAFT = "DRAFT"
    SENT = "SENT"
    RECEIVED = "RECEIVED"
    PARTIALLY_RECEIVED = "PARTIALLY_RECEIVED"
    CANCELLED = "CANCELLED"

class DiscountType(str, enum.Enum):
    PERCENTAGE = "PERCENTAGE"
    FIXED_AMOUNT = "FIXED_AMOUNT"

class OrderStatus(str, enum.Enum):
    PENDING = "PENDING"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"
    REJECTED = "REJECTED"

class PaymentMethod(str, enum.Enum):
    EFECTIVO = "EFECTIVO"
    MERCADOPAGO = "MERCADOPAGO"
    APP_COMIDA = "APP_COMIDA"
    TRANSFERENCIA = "TRANSFERENCIA"
    OTRO = "OTRO"

class ProductType(str, enum.Enum):
    RAW_MATERIAL = "RAW_MATERIAL"
    PRODUCT_INTERMEDIATE = "PRODUCT_INTERMEDIATE"
    PRODUCT_ELABORATED = "PRODUCT_ELABORATED"
    PRODUCT_PURCHASED = "PRODUCT_PURCHASED"